export const setQuiqChatContainerVisible = jest.fn();
export const setQuiqUserTakenMeaningfulAction = jest.fn();
export const setAccessToken = jest.fn();
export const getQuiqChatContainerVisible = jest.fn(() => true);
export const getQuiqUserTakenMeaningfulAction = jest.fn(() => true);
export const getQuiqUserIsSubscribed = jest.fn(() => true);
export const setQuiqUserIsSubscribed = jest.fn(() => {});
export const getAccessToken = jest.fn(() => 'access-token');
export const getTrackingId = jest.fn(() => 'tracking-id');
export const isStorageEnabled = jest.fn(() => true);
export const init = jest.fn();
